### ISSUE TITLE
Immich data resets every 30 days?

### ISSUE THREAD

**Issue by johnny2678** [friendlyFriend4000/prometheus-immich-exporter#11]
Hi! Thanks for this container.  I've got it all set up and working with Grafana.  It works great, but for some reason my data gets reset every 30 days?

I'm a complete prometheus noob so I'm not sure if it's an issue with the way prometheus is set up or this exporter and hoping someone here might be able to give me some pointers on where to look.

Thanks!

**Comment by Allram** [comment]
You need to set the retention timer for the Prometheus DB in the extra field on UnRaid Docker, or in the docker-compose if you are not using UnRaid.

T.ex:
`--storage.tsdb.retention.time=1y` for a 1 year retention of data

**Comment by johnny2678** [comment]
> `--storage.tsdb.retention.time=1y` for a 1 year retention of data 

Oh wow, I feel dumb. Wish I had asked this sooner!

Thanks!
